# Site settings
title: "Reservations"
email: "stc-reservations@yale.edu"
description: "Reservation is an open-source application for item loan management. It is developed by Yale STC."
baseurl: "http://yalestc.github.com/reservations"
url: "http://yalestc.github.com/reservations"

# Build settings
markdown: kramdown
permalink: pretty
